const ACTION_TYPES = { 
    ADD_TRANSACTION_LIST_START : "ADD_TRANSACTION_LIST_START",
    ADD_TRANSACTION_LIST_SUCCESS:"ADD_TRANSACTION_LIST_SUCCESS",
    ADD_TRANSACTION_LIST_FAILURE:"ADD_TRANSACTION_LIST_FAILURE",
    ADD_LISTS_START:"ADD_LISTS_START",
    ADD_LISTS_SUCCESS:"ADD_LISTS_SUCCESS",
    ADD_LISTS_FAILURE:"ADD_LISTS_FAILURE",
    DELETE_TRANSACTION:"DELETE_TRANSACTION",
    EDIT_TRANSACTION:"EDIT_TRANSACTION",
}
export default ACTION_TYPES;